<!-- Example showing the concept of Async_Await -->
 <script>
    var num=2;
    function funOne(num){
        return new Promise((resolve,reject)=>{
            if(num<=10)
                resolve(num*num);
            else
                reject(new Error("Number Exceeds"));
        });
    }
    async function myResult(){
        try{
            const res = await funOne(num);
            const res1 = await funOne(res);
            console.log(res1);
        }catch(error){
            console.log(error);
        }
    }
    myResult();
</script>